### ISSUE TITLE
Log input filename

### ISSUE THREAD

**Issue by ewels** [jfjlaros/dedup#12]
@Redmar-van-den-Berg wrote a lovely MultiQC module for this tool in https://github.com/ewels/MultiQC/pull/1795, but the [method for finding a sample name](https://github.com/ewels/MultiQC/blob/9c657a2a95901d9f3143cda64ffff18359cd8637/multiqc/modules/humid/humid.py#L48-L50) is a bit rough:

```python
# There is no sample name in the log, so we use the root of the
# file as sample name (since the filename is always stats.dat
name = f["root"]
```

It would be much nicer if the `stats.dat` file could log one or two more things - most importantly, the input file name(s). That way, the file can be interpreted by itself without needing directory structure for context.

**Comment by jfjlaros** [comment]
Thank you for this suggestion.

Would something like this be acceptable?

```txt
input: R1.fq R2.f1 R3.fq
total: 8
usable: 7
unique: 4
clusters: 3
```

> It would be much nicer if the stats.dat file could log one or two more things

Which other things do you have in mind?

**Comment by ewels** [comment]
Given that the file seems to already be valid YAML (at least [the example](https://github.com/ewels/MultiQC_TestData/blob/master/data/modules/humid/test_sample/stats.dat) from @Redmar-van-den-Berg is), how about sticking to YAML? Would make downstream usage super easy for people.

So then, something like this:

```yaml
input: [R1.fq, R2.f1, R3.fq]
total: 8
usable: 7
unique: 4
clusters: 3
```

or this:

```yaml
input:
  - R1.fq
  - R2.f1
  - R3.fq
total: 8
usable: 7
unique: 4
clusters: 3
```

For other stuff, I can refer to my now ancient and slightly-ranty [blog post](http://tallphil.co.uk/writing-good-log-files/) on the topic, but generally I really appreciate things like the software name, software version number, the command / parameters used. So if you end up with the results file in isolation you're able to know how it was generated.

**Comment by jfjlaros** [comment]
Well, it is a text file that happens to conform to the YAML standard, but we can pretend that this was intentional.

> I really appreciate things like the software name, software version number, the command / parameters used.

I will see what I can do. Do you have any preferences for key names?

**Comment by ewels** [comment]
A happy accident 😊 No preference. Thanks so much!

**Comment by jfjlaros** [comment]
I added an [option](https://github.com/jfjlaros/HUMID/commit/34f8eaca2a882f146dcec3a3e38d70d3d3210486) to write a separate metadata file.


Such a file would look like this:

```yml
name: humid
version: 1.0.2
parameters:
  word_length: 24
  allowed_mismatches: 1
  log_name: /dev/stderr
  dir_name: out
  run_statistics: false
  filter_duplicates: true
  annotate_fastq_files: false
  use_edit_distance: false
  use_maximum_clustering: false
  write_metadata: true
  files:
    - data/R1.fq.gz
    - data/R2.fq.gz
    - data/R3.fq.gz
```

Would this work nicely with MultiQC?
